sudo: required

services:
  - docker

script:
- curl -o http://storage.googleapis.com/kubernetes-helm/helm-${TRAVIS_TAG:-v2.0.0}-linux-amd64.tar.gz
- tar -xvf /tmp/helm-${TRAVIS_TAG:-v2.0.0}-linux-amd64.tar.gz
- cp linux-amd64/helm ./helm
- chmod +x ./helm

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=supergiant/helm-worker
  - export TAG=`if [ -z "$TRAVIS_TAG" ] && [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; elif [ -z "$TRAVIS_TAG" ] && [ "$TRAVIS_BRANCH" != "master" ]; then echo "unstable-${TRAVIS_BRANCH}"; else echo $TRAVIS_TAG ; fi`
  - docker build -t $REPO:$TAG .
  - docker push $REPO
